theme: minima
title: NeuroGDA
description: A website for the NeuroGDA seminar series
author: Ola Rutkowska & Krzysztof Basiński
header_pages: ['whatis.md','previous.md', 'gallery.md', 'contribute.md']
